### ISSUE TITLE
MinosConfig replica

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/api_gateway_common#2]
Example of MinosConfig:
``` yaml
service:
    name: Order
rest:
    host: localhost
    port: 8900
    endpoints:
        - name: AddOrder
          route: /order
          method: POST
          controller: minos.services.OrderService
          action: add_order
discovery:
    host: localhost
    port: 8080
    path: /discover
    endpoints:
        - name: Discover
          route: /discover
          method: GET
          controller: minos.services.DiscoveryService
          action: discover
        - name: Subscribe
          route: /subscribe
          method: POST
          controller: minos.services.DiscoveryService
          action: subscribe
        - name: Unsubscribe
          route: /unsubscribe
          method: POST
          controller: minos.services.DiscoveryService
          action: unsubscribe
        - name: SystemHealth
          route: /system/health
          method: GET
          controller: minos.services.DiscoveryService
          action: system_health
    db:
        host: localhost
        port: 6379
        password: None
```

**Comment by vladyslav-fenchak** [comment]
@andrea-mucci How do you see it?

**Comment by andrea-mucci** [comment]
Is ok, but i guess that the `service` parameter is useless.
The API Gateway is not a service but is a component, so:

```yaml
rest:
    host: localhost
    port: 8900
    endpoints:
        - name: AddOrder
          route: /order
          method: POST
          controller: minos.services.OrderService
          action: add_order
discovery:
    host: localhost
    port: 8080
    path: /discover
    endpoints:
        - name: Discover
          route: /discover
          method: GET
          controller: minos.services.DiscoveryService
          action: discover
        - name: Subscribe
          route: /subscribe
          method: POST
          controller: minos.services.DiscoveryService
          action: subscribe
        - name: Unsubscribe
          route: /unsubscribe
          method: POST
          controller: minos.services.DiscoveryService
          action: unsubscribe
        - name: SystemHealth
          route: /system/health
          method: GET
          controller: minos.services.DiscoveryService
          action: system_health
    db:
        host: localhost
        port: 6379
        password: None
```

we can remove it, at the moment

the rest of the configurations parameters are fine.
